name: AVL_tree


on:
  push

jobs:
  windows-build:
    runs-on: windows-2019
    steps:
        - uses: actions/checkout@v2
        - run: |
            mkdir build
            cmake -Bbuild -G "Visual Studio 16 2019"       
            cmake --build build
            .\build\bin\test_avl_tree.exe 
    
  linux-build:
    runs-on: ubuntu-24.04
    steps:
        - uses: actions/checkout@v2
        - run: |
            mkdir build
            cmake -Bbuild -G "Unix Makefiles"       
            cmake --build build
            ./build/bin/test_AVL_TREE
